[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
key = "T"
mods = "Alt"

[keyboard.bindings.command]
args = ["-c", "kill -USR1 $PPID"]
program = "sh"

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[font]
size = 12.0

[font.bold]
family = "Rec Mono Linear"
style = "Bold"

[font.bold_italic]
family = "Rec Mono Linear"
style = "Bold Italic"

[font.italic]
family = "Rec Mono Linear"
style = "Italic"

[font.normal]
family = "Rec Mono Linear"
style = "Regular"

[window]
opacity = 0.95

[keyboard]
